Update reeek.yml

diff --git a/.github/workflows/reeek.yml b/.github/workflows/reeek.yml
--- a/.github/workflows/reeek.yml
+++ b/.github/workflows/reeek.yml
@@ -22,4 +22,10 @@ jobs:
         run: gem install reek
 
       - name: Run Reek
-        run: reek --failure-exit-code
+        run: |
+          set -e
+          reek
+          if [ $? -ne 0 ]; then
+            echo "Reek analysis failed"
+            exit 1
+          fi
